services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
       - /d/Malifax/laravel_storage:/var/www/html/storage
    ports:
      - "8000:8000"
    networks:
      - laravel
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
